# Generated by Django 2.2.1 on 2019-05-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_traded_quantity', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='KeyExecutives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('yob', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_executives', to='stock.Stock')),
            ],
        ),
    ]
