# Generated by Django 2.2.1 on 2019-05-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyExecutives',
            new_name='KeyExecutive',
        ),
    ]
