# Generated by Django 2.2.1 on 2019-05-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190522_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stock.Stock'),
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stock.Stock')),
            ],
        ),
    ]
