# Generated by Django 2.2.1 on 2019-05-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190526_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tweet', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='stock.Stock')),
            ],
        ),
    ]
